services:
  - type: web
    name: Rakshan-AI
    env: node
    plan: free
    buildCommand: npm install --prefix backend && npm install --legacy-peer-deps --prefix frontend && cd frontend && npm run build
    startCommand: node backend/server.js
    healthCheckPath: /api/health